# Generated by Django 4.2.3 on 2023-07-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_01', '0010_alter_order_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
    ]
