# Generated by Django 4.2.3 on 2023-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_01', '0011_remove_shippingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='postalCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
