# Generated by Django 4.2.3 on 2023-07-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_01', '0012_order_address_order_city_order_postalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
