# Generated by Django 4.2.3 on 2023-07-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_01', '0013_order_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
